FROM scratch
MAINTAINER \
[Adam Miller <maxamillion@fedoraproject.org>] \
[Patrick Uiterwijk <patrick@puiterwijk.org>]
ENV DISTTAG=f26container FGC=f26 FBR=f26
ADD fedora-26-ppc64le-20171114.tar.xz /
